### ISSUE TITLE
New Sonarcloud coverage rule

### ISSUE THREAD

**Issue by MioRtia** [powsybl/powsybl-tutorials#10]
* **Do you want to request a *feature* or report a *bug*?**
Neither.

* **What is the current behavior?**
Currently, Sonarcloud refuses PR where the implemented code is less than 80% covered by tests.

* **What is the motivation / use case for changing the behavior?**
This is not a relevant behaviour here for tutorials. What should be done about it?

* **Please tell us about your environment:**
  - powsybl-tutorials version: 1.0.0 
  - OS Version: Linux

**Comment by mathbagu** [comment]
Fixed by adding a quality gate without code coverage requirements.
